### ISSUE TITLE
Modifying user settings without permission

### ISSUE THREAD

**Issue by user18130814200115-2** [strukturart/osm-map#10]
The app enables screen lock automatically. If screen lock is not set (and no pin is set the pin is 0000) it is enabled though the settings still show it is off. This problem is mediated by enabling and then disabling screen lock in the settings.

Hardware: Nokia 8110 dual sim
Software: Gerda os custom rom
Source: Bhackers store

**Comment by strukturart** [comment]
that was the case with the old version, with the new one I removed the "wrong track". please install the app with the bHacker client that you always have the current version.
