### ISSUE TITLE
information about osm-map.json 

### ISSUE THREAD

**Issue by rheotome-continuo** [strukturart/osm-map#12]
Hi, can you tell me where the **osm-map.json** file should be saved? I copied yours to `/data/local/webapps/b40a6b3b-861e-4df4-b869-71003fd56b8e/` but it isn't found. Do I need to repack the zipfile?

And what does **marker_name** and **default_position** in the osm-map.json file mean?

Thank you so much.

**Comment by strukturart** [comment]
you must store osm-map.json in the internal or in the sd card. marker_name this is the name of the marker that you can predefine, default_position is the position that is set if the device cannot locate you.

**Comment by jm42** [comment]
Does it read the configuration file from the internal memory, or just the SD card?

From [here](https://github.com/strukturart/osm-map/blob/c558e9d413b684a70e02b50cd7b9abd476a2f974/application/app.js#L248) seems only sdcard search.
