### ISSUE TITLE
Cant open app because of no geolocation available

### ISSUE THREAD

**Issue by Warlo** [strukturart/osm-map#2]
I have a Nokia 8110 4G with GerdaOS freshly installed, downloaded and installed OSM-Map and when i open the app it asks me to allow or deny geolocation. since GerdaOS doesnt have Geolocation (at least on my install, cant make it work for Gmaps, OSM or any other app that requires it, just keeps searching but never finds my location) it will never start the app. I was wondering if it would be possible that by clicking in "Deny" it would be possible to use OSM map functionality without geolocation.

Software version is 13.00.17.01

**Comment by strukturart** [comment]
I have also GerdaOS installed and have Geolocation. Maybe it is an connection issue, can you pls can you please try it out of the house with enabled wifi/data connection?

**Comment by strukturart** [comment]
@Warlo it works ?

**Comment by Warlo** [comment]
Hey! It does with lte on!strukturart/osm-map wrote:@Warlo it works ?
