### ISSUE TITLE
Add shortcut reminder like on Browser

### ISSUE THREAD

**Issue by pherjung** [strukturart/osm-map#3]
It could be nice to have a small area dedicated for all shortcuts your used. Perhaps, should be interesting to show permanently one small shortcut at screen's bottom with a question mark.
If you press on this button, it will show temporary much more shortcuts.

![Browser](https://user-images.githubusercontent.com/5952038/66465929-1924c900-ea82-11e9-86ed-7a281b4c0ec8.png)

![Example](https://user-images.githubusercontent.com/5952038/66471492-afa9b800-ea8b-11e9-8f9a-93e4b20d1b51.png)

**Comment by strukturart** [comment]
pls reinstall the app
---
if you press 0 a manual[ :- ) ] apperars

**Comment by strukturart** [comment]
@pherjung it is solved ?
