### ISSUE TITLE
Provide the application.zip in github releases...

### ISSUE THREAD

**Issue by Simon-Laux** [strukturart/osm-map#4]
.. instead of from the build folder

**Comment by jm42** [comment]
What happen with this? I think is a reasonable petition.

What about a build script for automation?

**Comment by strukturart** [comment]
@jm42  https://github.com/strukturart/osm-map/releases

> What about a build script for automation?
I don't know how

**Comment by Simon-Laux** [comment]
you can copy paste some stuff from here https://github.com/deltachat/delta.chat-kaiOs/blob/master/tools/package @strukturart

**Comment by strukturart** [comment]
I develop the app directly on the phone because i don't have a test environment for kaios. When the app has reached a certain status I copy it from my phone to my computer, commit it and push it to github.

**Comment by Simon-Laux** [comment]
> What happen with this? I think is a reasonable petition.

he did in fact release it: https://github.com/strukturart/osm-map/releases
