### ISSUE TITLE
Markers are not saved

### ISSUE THREAD

**Issue by baltbreeze** [strukturart/osm-map#6]
Hello!
I'm using your awesome app on the nokia 8110 phone with 17 firmware on it.
When I try to save current location to marker (button "5"), the promt with marker name (current date and time) appears. 
However when I accept it no marker is created. I've checked it many times.
Also, some bugs:
1) the path to osm-map.json in the source code differs: at some places it's on the root of sdcard, but in other it's related to /osm-map/ directory of sdcard. I've corrected it manually, but other users may have problems.
2) when the app is starting and no coords are available, there's error shown:
"TypeError: myMarker.setLatLng is not a function" Line:456 of app.js
This error also appears when you press button "6" in the place where gps is not available.

P.S. Could you describe how to use the "measure distance" tool? It looks cool but I need some help. 
Thanks for your amazing work!

**Comment by strukturart** [comment]
thanks for the feedback, have you installed the latest version?
I will fix the bug in the near future. To use the measuring tool, press key 7 and then set two points with the cursor.

**Comment by baltbreeze** [comment]
Yes, I am using the latest build.
Regards,

**Comment by strukturart** [comment]
Can you see the menu when you press 3 ?

**Comment by baltbreeze** [comment]
Yes, I have that menu working and two example marker records in your osm-map.json were successfully deleted by the long button press.  However, no new markers are added as I described above.

**Comment by baltbreeze** [comment]
Update: I've run the app multiple times today with the success of saving markers.
Run the app and don't press any buttons, **wait for the current position shown**, and the markers will work if you got the coords.
if you tired of waiting and press button 1 to seek the position before it's shown when the app is starting - at half of times you will get an error "TypeError: myMarker.setLatLng is not a function" Line:456 of app.js, then the app is misbehaving, markers not saved even if your next try pressing button 1 will get the coords with success. Only restart the app solves the problem.
I am testing that under the roof and gps is unstable in these conditions, however I think some exceptions in code may solve the problem with errors.

**Comment by strukturart** [comment]
The app is rather designed for the outdoor area. The position save as marker is meant for example for the following situations: you are at a place and want to remember it or you have found something using the search function and want to remember it for later.

**Comment by strukturart** [comment]
@baltbreeze can you please test the new build.

**Comment by baltbreeze** [comment]
I've tested new build. It seems that marker problem is solved!
To avoid "TypeError: myMarker.setLatLng is not a function" message I suggest small workaround:
line 541 of app.js:
if (option == "update_marker") {
change to:
if (option == "update_marker" && current_lat != "") {
The error is no longer shown when coords are not available.
Regards,
